#ifndef CUBE_BLOCK_HPP
#define CUBE_BLOCK_HPP

#include <cstdint>

namespace cube {

    enum class Block : uint16_t {
        Air = 0,

        GrassBlock,
        SnowGrass,
        Dirt,
        Sand,
        RedSand,
        CoarseDirt,

        Clay,
        Mud,
        Gravel,

        Stone,
        Sandstone,
        RedSandstone,
        Andesite,
        Calcite,
        Hardstone,
        Diorite,
        Tuff,
        Obsidian,

        CobbledHardstone,
        Cobblestone,
        MossyCobblestone,

        Ice,
        BlueIce,
        Snow,

        Cactus,
        CactusFlower,

        Melon,
        Pumpkin,

        BrainCoral,
        BrainCoralBlock,
        BrainCoralFan,
        BubbleCoral,
        BubbleCoralBlock,
        BubbleCoralFan,
        FireCoral,
        FireCoralBlock,
        FireCoralFan,
        HornCoral,
        HornCoralBlock,
        HornCoralFan,
        TubeCoral,
        TubeCoralBlock,
        TubeCoralFan,

        DeadBrainCoral,
        DeadBrainCoralBlock,
        DeadBrainCoralFan,
        DeadBubbleCoral,
        DeadBubbleCoralBlock,
        DeadBubbleCoralFan,
        DeadFireCoral,
        DeadFireCoralBlock,
        DeadFireCoralFan,
        DeadHornCoral,
        DeadHornCoralBlock,
        DeadHornCoralFan,
        DeadTubeCoral,
        DeadTubeCoralBlock,
        DeadTubeCoralFan,

        BrownMushroom,
        RedMushroom,
        Bush,
        DeadBush,
        CactusBush,
        Fern,
        LargeFern,
        FireflyBush,
        Grass,
        CaveVine,
        ShortDryGrass,
        DryGrass,
        SugarCane,
        SweetBerry,
        TallGrass,
        DryTallGrass,
        Vine,
        Wildflowers,

        Kelp,
        SeaGrass,
        TallSeaGrass,

        Allium,
        BlueOrchid,
        CornFlower,
        Dandelion,
        GoldenDandelion,
        Lilac,
        OrangeTulip,
        OxeyeDaisy,
        Peony,
        PinkTulip,
        Poppy,
        RedTulip,
        RoseBush,
        SporeBlossom,
        Sunflower,
        WhiteTulip,

        CoalOre,
        CopperOre,
        DiamondOre,
        EmeraldOre,
        GoldOre,
        IronOre,
        LapisOre,
        RedOre,

        HardrockCoalOre,
        HardrockCopperOre,
        HardrockDiamondOre,
        HardrockEmeraldOre,
        HardrockGoldOre,
        HardrockIronOre,
        HardrockLapisOre,
        HardrockRedOre,

        BlackTerracotta,
        BlueTerracotta,
        BrownTerracotta,
        CyanTerracotta,
        GrayTerracotta,
        GreenTerracotta,
        LightBlueTerracotta,
        LightGrayTerracotta,
        LimeTerracotta,
        MagentaTerracotta,
        OrangeTerracotta,
        PinkTerracotta,
        PurpleTerracotta,
        RedTerracotta,
        WhiteTerracotta,
        YellowTerracotta,
        Terracotta,

        AzaleaLeaves,
        AzaleaLog,
        AzaleaPlant,

        AzaleaFloweringLeaves,
        AzaleaFloweringPlant,

        AcaciaLeaves,
        AcaciaLog,
        AcaciaSapling,
        BirchLeaves,
        BirchLog,
        BirchSapling,
        CherryLeaves,
        CherryLog,
        CherrySapling,
        DarkOakLeaves,
        DarkOakLog,
        DarkOakSapling,
        JungleLeaves,
        JungleLog,
        JungleSapling,
        OakLeaves,
        OakLog,
        OakSapling,
        PaleOakLeaves,
        PaleOakLog,
        PaleOakSapling,
        SpruceLeaves,
        SpruceLog,
        SpruceSapling,

        Water,
        Lava,

        Bedrock = 255,
    };

}

#endif //CUBE_BLOCK_HPP
